//   ==================================================================
//   >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
//   ------------------------------------------------------------------
//   Copyright (c) 2006-2011 by Lattice Semiconductor Corporation
//   ------------------------------------------------------------------
//   ALL RIGHTS RESERVED
//
//   IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LATTICEMICO SYSTEM.
//
//   Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      pursuant to the terms of the Lattice Semiconductor Corporation
//      Open Source License Agreement.
//
//   Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify the userfs design for consistency and functionality through
//      the use of formal verification methods.
//
//   --------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
//   --------------------------------------------------------------------
//
//      Project:           MemoryCardTest
//      File:              MemoryCardTest_inst.v
//      Date:              …, 21 3 2018 23:36:31 JST
//      Version:           2.1
//      Targeted Family:   XP2
//
//   =======================================================================

MemoryCardTest MemoryCardTest_u ( 
.clk_i(clk_i),
.reset_n(reset_n)
, .uartSIN(uartSIN) // 
, .uartSOUT(uartSOUT) // 
, .gpioPIO_OUT(gpioPIO_OUT) // [2-1:0]
, .spiMISO_MASTER(spiMISO_MASTER) // 
, .spiMOSI_MASTER(spiMOSI_MASTER) // 
, .spiSS_N_MASTER(spiSS_N_MASTER) // [1-1:0]
, .spiSCLK_MASTER(spiSCLK_MASTER) // 
);
