<?xml version="1.0"?>

<PacDesignData>

<DocFmtVersion>1</DocFmtVersion>
<DeviceType>ispPAC-POWR607</DeviceType>

<CreatedBy>PAC-Designer 6.32.1347</CreatedBy>

<FuseMap>11111111111111111111111111111110111101110101111011101011110111010111101110101111011101011110111010011111111111111111111111111111111111111111111111111111111111111111111111111111110110010000000000000000000000000000000000000011111111111111111111111111111111</FuseMap>

<SecurityFuse>0</SecurityFuse>

<SummaryInformation>
<Title></Title>
<Subject></Subject>
<Author>Unknown User</Author>
<Keywords>ispPAC-POWR607</Keywords>
<Comments>
<![CDATA[
]]>
</Comments>
</SummaryInformation>

<GeneralPurposeLogicEnvOption>
   <PACMode>0</PACMode>
   <HDLMode>0</HDLMode>
   <PreferSynthesis>0</PreferSynthesis>
   <PROJName></PROJName>
   <PROJDIR></PROJDIR>
</GeneralPurposeLogicEnvOption>

<CoTest>
   <TopModuleName></TopModuleName>
   <TopFileName></TopFileName>
   <TestFile>
   </TestFile>
</CoTest>
<CPLDTest>
   <TopModuleName></TopModuleName>
   <TopFileName></TopFileName>
</CPLDTest>

<RemoteFileList>
</RemoteFileList>

<SymbolicSchematicData>
  <Symbol>
    <SymKey>460</SymKey>
    <NameText>VMON1 Monitoring Type</NameText>
    <Value>0</Value>
  </Symbol>
  <Symbol>
    <SymKey>461</SymKey>
    <NameText>VMON2 Monitoring Type</NameText>
    <Value>0</Value>
  </Symbol>
  <Symbol>
    <SymKey>462</SymKey>
    <NameText>VMON3 Monitoring Type</NameText>
    <Value>0</Value>
  </Symbol>
  <Symbol>
    <SymKey>463</SymKey>
    <NameText>VMON4 Monitoring Type</NameText>
    <Value>0</Value>
  </Symbol>
  <Symbol>
    <SymKey>464</SymKey>
    <NameText>VMON5 Monitoring Type</NameText>
    <Value>0</Value>
  </Symbol>
  <Symbol>
    <SymKey>465</SymKey>
    <NameText>VMON6 Monitoring Type</NameText>
    <Value>0</Value>
  </Symbol>
</SymbolicSchematicData>

<PscSequenceControllerPrgm>

<CreatedBy>LogiBuilder 6.32.1347</CreatedBy>
<LockedOutForAbelEditing>0</LockedOutForAbelEditing>
<AbelSavedByUser>0</AbelSavedByUser>
<PscStateMachineEncoding>0</PscStateMachineEncoding>
<PscFlipFlopSynthesisType>0</PscFlipFlopSynthesisType>
<PscCanDeleteLastHalt>0</PscCanDeleteLastHalt>
<PscIODatabase>
  <TargetSystemID>6</TargetSystemID>
  <TargetSystemName></TargetSystemName>
  <PscIO>
    <PscIOID>0</PscIOID>
    <Idx>0</Idx>
    <DatasheetName>VMON1</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>1</PscIOID>
    <Idx>1</Idx>
    <DatasheetName>VMON2</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>1</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>2</PscIOID>
    <Idx>2</Idx>
    <DatasheetName>VMON3</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>2</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>3</PscIOID>
    <Idx>3</Idx>
    <DatasheetName>VMON4</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>3</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>4</PscIOID>
    <Idx>4</Idx>
    <DatasheetName>VMON5</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>4</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>5</PscIOID>
    <Idx>5</Idx>
    <DatasheetName>VMON6</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>5</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>12</PscIOID>
    <Idx>6</Idx>
    <DatasheetName>IN1</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>13</PscIOID>
    <Idx>7</Idx>
    <DatasheetName>IN2</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>0</PinType>
    <PinTypeAsText>Input</PinTypeAsText>
    <PinnamePos>1</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>20</PscIOID>
    <Idx>12</Idx>
    <DatasheetName>HVOUT1</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>1</PinType>
    <PinTypeAsText>Output, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>21</PscIOID>
    <Idx>13</Idx>
    <DatasheetName>HVOUT2</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>1</PinType>
    <PinTypeAsText>Output, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>1</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>22</PscIOID>
    <Idx>14</Idx>
    <DatasheetName>IN_OUT3</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>11</PinType>
    <PinTypeAsText>IN_OUT: Output, registered, JK flip-flop</PinTypeAsText>
    <GpioType>0</GpioType>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>23</PscIOID>
    <Idx>15</Idx>
    <DatasheetName>IN_OUT4</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>11</PinType>
    <PinTypeAsText>IN_OUT: Output, registered, JK flip-flop</PinTypeAsText>
    <GpioType>0</GpioType>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>1</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>24</PscIOID>
    <Idx>16</Idx>
    <DatasheetName>IN_OUT5</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>11</PinType>
    <PinTypeAsText>IN_OUT: Output, registered, JK flip-flop</PinTypeAsText>
    <GpioType>0</GpioType>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>2</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>25</PscIOID>
    <Idx>17</Idx>
    <DatasheetName>IN_OUT6</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>11</PinType>
    <PinTypeAsText>IN_OUT: Output, registered, JK flip-flop</PinTypeAsText>
    <GpioType>0</GpioType>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>3</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>26</PscIOID>
    <Idx>18</Idx>
    <DatasheetName>IN_OUT7</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>11</PinType>
    <PinTypeAsText>IN_OUT: Output, registered, JK flip-flop</PinTypeAsText>
    <GpioType>0</GpioType>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>4</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>86</PscIOID>
    <Idx>19</Idx>
    <DatasheetName>PLD_PWRDN</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>1</PinType>
    <PinTypeAsText>Output, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>2</ResetMode>
    <ResetModeAsText>Set high</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>28</PscIOID>
    <Idx>20</Idx>
    <DatasheetName>TIMER1_GATE</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>5</PinType>
    <PinTypeAsText>Output, registered, D flip-flop</PinTypeAsText>
    <TimerReservedForOutput>0</TimerReservedForOutput>
    <OutputType>1</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>29</PscIOID>
    <Idx>21</Idx>
    <DatasheetName>TIMER2_GATE</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>5</PinType>
    <PinTypeAsText>Output, registered, D flip-flop</PinTypeAsText>
    <TimerReservedForOutput>0</TimerReservedForOutput>
    <OutputType>1</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>30</PscIOID>
    <Idx>22</Idx>
    <DatasheetName>TIMER3_GATE</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>5</PinType>
    <PinTypeAsText>Output, registered, D flip-flop</PinTypeAsText>
    <TimerReservedForOutput>0</TimerReservedForOutput>
    <OutputType>1</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>31</PscIOID>
    <Idx>23</Idx>
    <DatasheetName>TIMER4_GATE</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>5</PinType>
    <PinTypeAsText>Output, registered, D flip-flop</PinTypeAsText>
    <TimerReservedForOutput>0</TimerReservedForOutput>
    <OutputType>1</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>65</PscIOID>
    <Idx>24</Idx>
    <DatasheetName>NODE1</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>66</PscIOID>
    <Idx>25</Idx>
    <DatasheetName>NODE2</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>67</PscIOID>
    <Idx>26</Idx>
    <DatasheetName>NODE3</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>68</PscIOID>
    <Idx>27</Idx>
    <DatasheetName>NODE4</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>69</PscIOID>
    <Idx>28</Idx>
    <DatasheetName>NODE5</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>70</PscIOID>
    <Idx>29</Idx>
    <DatasheetName>NODE6</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>71</PscIOID>
    <Idx>30</Idx>
    <DatasheetName>NODE7</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
  <PscIO>
    <PscIOID>72</PscIOID>
    <Idx>31</Idx>
    <DatasheetName>NODE8</DatasheetName>
    <LogicPolarity>1</LogicPolarity>
    <PinType>9</PinType>
    <PinTypeAsText>Node, registered, JK flip-flop</PinTypeAsText>
    <OutputType>0</OutputType>
    <ResetMode>0</ResetMode>
    <ResetModeAsText>Don't care</ResetModeAsText>
    <PinnamePos>0</PinnamePos>
  </PscIO>
</PscIODatabase>

<PscProgram>

  <MaxProgramSize>128</MaxProgramSize>
  <ProgramSize>3</ProgramSize>
<PscInstruction>
  <StepIdx>0</StepIdx>
  <StatementAsText></StatementAsText>
  <OpcodeMnemonic>startup sequence</OpcodeMnemonic>
  <Opcode>9</Opcode>
  <Interruptible>0</Interruptible>
<Comments>
<![CDATA[ispPAC-POWR607 reset]]>
</Comments>
<Lines>1</Lines>
<OutputControl>
</OutputControl>
<OutputControlText></OutputControlText>
</PscInstruction>

<PscInstruction>
  <StepIdx>1</StepIdx>
  <StatementAsText></StatementAsText>
  <OpcodeMnemonic>shutdown sequence</OpcodeMnemonic>
  <Opcode>10</Opcode>
  <Interruptible>0</Interruptible>
<Comments>
<![CDATA[]]>
</Comments>
<Lines>1</Lines>
<OutputControl>
</OutputControl>
<OutputControlText></OutputControlText>
</PscInstruction>

<PscInstruction>
  <StepIdx>2</StepIdx>
  <StatementAsText></StatementAsText>
  <OpcodeMnemonic>end-of-program</OpcodeMnemonic>
  <Opcode>100</Opcode>
  <Interruptible>0</Interruptible>
<Comments>
<![CDATA[]]>
</Comments>
<Lines>1</Lines>
<OutputControl>
</OutputControl>
<OutputControlText></OutputControlText>
</PscInstruction>

</PscProgram>

<PscExceptionTable>

  <ExceptionTableSize>1</ExceptionTableSize>
  <PscExceptionTableEntry>
    <Idx>0</Idx>
    <PscExceptionType>100</PscExceptionType>
  <PscBooleanExpression>
  <PscBooleanExpressionString></PscBooleanExpressionString>
   <ItemCount>0</ItemCount>
  </PscBooleanExpression>
    <PscOutputListAsString>{no outputs specified}</PscOutputListAsString>
<PscOutputList>
</PscOutputList>
    <GotoMode>0</GotoMode>
    <GotoNextStep>0</GotoNextStep>
<Comments>
<![CDATA[]]>
</Comments>
  </PscExceptionTableEntry>

</PscExceptionTable>

<PscRandomLogicTable>

  <Size>1</Size>
  <HasTimerEqn>0</HasTimerEqn>
  <PscRandomLogicTableEntry>
    <Idx>0</Idx>
    <Type>100</Type>
    <CanEdit>1</CanEdit>
<Comments>
<![CDATA[]]>
</Comments>
  </PscRandomLogicTableEntry>

</PscRandomLogicTable>

</PscSequenceControllerPrgm>

</PacDesignData>

